# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProtoFiles/PhysicalConstants/Fundamental.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.ProtoFiles/PhysicalConstants/Fundamental.proto\x12\x1cPhysicalConstantsFundamental\"\xf8\x01\n\x14\x46undamentalConstants\x12N\n\tconstants\x18\x01 \x03(\x0b\x32;.PhysicalConstantsFundamental.FundamentalConstants.Constant\x1a\x8f\x01\n\x08\x43onstant\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\x12\x18\n\x0buncertainty\x18\x03 \x01(\x02H\x00\x88\x01\x01\x12\x12\n\x05units\x18\x04 \x01(\tH\x01\x88\x01\x01\x12\x13\n\x06symbol\x18\x05 \x01(\tH\x02\x88\x01\x01\x42\x0e\n\x0c_uncertaintyB\x08\n\x06_unitsB\t\n\x07_symbolb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ProtoFiles.PhysicalConstants.Fundamental_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FUNDAMENTALCONSTANTS._serialized_start=81
  _FUNDAMENTALCONSTANTS._serialized_end=329
  _FUNDAMENTALCONSTANTS_CONSTANT._serialized_start=186
  _FUNDAMENTALCONSTANTS_CONSTANT._serialized_end=329
# @@protoc_insertion_point(module_scope)
